export const ADD_WORKSPACE = "ADD_WORKSPACE";

export const SET_WORKSPACES = "SET_WORKSPACES";

export const SET_ACTIVE_WS_PROJECT = "SET_ACTIVE_WS_PROJECT";

export const DELETE_WORKSPACE = "DELETE_WORKSPACE";